apiVersion: v1
kind: Service
metadata:
  name: reactapp-service
spec:
  selector:
    app: doingtest 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 4000
    nodePort: 31111