name: Build
on:
  push:
    branches:
      - dev
      - main
      - master
  pull_request:
    branches:
      - main
      - dev
      - master

jobs:
   runaction:
      runs-on: ubuntu-latest 

      steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
     
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/${{ secrets.DOCKERHUB_USERNAME }}/mydockerapp:${{ github.sha }} .
     
      - name: Run the image in a container
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/mydockerapp:${{ github.sha }}
          run: |
            echo "runing the docker image"

