name: Build
on:
  push:
    branches:
      - codequality
      - main
      - master
  pull_request:
    branches:
      - main
      - codequality
      - master

jobs:
  run-action:
    name: Run action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci
      
      - name: code quality
        run: npx eslint src/
        
      - name: Build
        run: npm run build
      - name: Test and coverage
        run: npm run test

       
