name: Build
on:
  push:
    branches:
      - codequality
      - main
      - master
  pull_request:
    branches:
      - main
      - codequality
      - master
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: stefanoeb/eslint-action@1.0.2
        with:
          files: src/
       
