name: Build
on:
  push:
    branches:
      - dev
      - main
      - master
  pull_request:
    branches:
      - main
      - dev
      - master

jobs:
   runaction:
      runs-on: ubuntu-latest 
      steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
     # - name: Test and coverage
     #   run: npm run test
      - name: Run my action
        uses: ./
        with:
          start: yarn start
          wait-on: 'http://localhost:3000'
       
