name: Build
on:
  push:
    branches:
      - dev
      - main
      - master
  pull_request:
    branches:
      - main
      - dev
      - master

jobs:
   runaction:
      runs-on: ubuntu-latest 

      steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
     
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
     
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mydockerapp:latest
     
      - name: Run the image in a container
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/mydockerapp:latest
          run: docker run --name Sapna1 -d -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/mydockerapp

