name: Continuous Deployment

on:
  push:
    branches: [ featureenv ]
  pull_request:
    branches: [ featureenv ]
  #workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build artifacts
        run: npm run build
      - name: deploy artifacts
        run: yarn start
    
  DeployDev:
    name: Deploy to Dev 
    #if: github.event_name == 'pull_request'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Development
      url: 'http://dev.myapp.com'
    steps:
      - name: Build artifacts
        run: npm run build
      - name: deploy artifacts
        run: yarn start
