name: Continuous Deployment

on:
  push:
    branches: [ env ]
  pull_request:
    branches: [ env ]
  #workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build artifacts
        run: npm run build
    
  DeployDev:
    name: Deploy to Dev 
    #if: github.event_name == 'pull_request'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Development
      url: 'http://dev.myapp.com'
    steps:
      - name: Deploy
        run: yarn start
