name: Continuousintegration
on:
  push:
    branches:
      - deploy
      - main
      - master
  pull_request:
    branches:
      - main
      - deploy
      - master

jobs:
  job1:
    runs-on: 'ubuntu-latest'
    name: scriptlanguageanalyse
    
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ['Javascript']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

    #  - name: Build artifacts
     #   run: npm run build
     # - name: Test and coverage
     #   run: npm run test
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{matrix.language}}"
          upload: False
          output: sarif-results
  job2:
     needs: job1
     runs-on: 'ubuntu-latest'     
     steps:
      - name: Build artifacts
        run: npm run build

  job3:
     needs: job2
     runs-on: 'ubuntu-latest'     
     steps:
      - name: Unittesting and coverage
        run: npm run test
       
